runtime: python310  # Use Python 3.10 runtime

entrypoint: gunicorn -b :$PORT app.py:app  # Replace 'your_app_name' with the name of your Python app


env_variables:
  DB_HOST: "458900:asia-east1:k2003"  # Google Cloud SQL connection name
  DB_PORT: "3306"  # MySQL default port
  DB_NAME_PUBLIC: "iwb_public"  # Your public database name
  DB_NAME_PRIVATE: "iwb_private"  # Your private database name
  DB_PASSWORD: "59482807"  # Your database password
  GOOGLE_CLOUD_PROJECT: "458900"  # Your Google Cloud project ID



handlers:
  - url: /static
    static_dir: static  # Serve static files from the 'static' directory
  - url: /.*
    script: auto  # Handle all other routes by the application
